import sqlite3
import os
from database import init_db_schema, get_db_connection

# Curated authentic Nagpur destinations with exact Lat/Lng coordinates, hidden gem markers, and nearby food links
NAGPUR_DESTINATIONS = [
    {
        "name": "Futala Lake Promenade",
        "category": "Nature",
        "description": "Famous for its vibrant waterfront, scenic sunset views over the water, and local evening food street culture. Constructed originally by the Bhonsle rulers.",
        "location": "Telankhedi, Nagpur, Maharashtra",
        "estimated_budget": 300,
        "budget_tier": "under_500",
        "ideal_duration_hours": 2.5,
        "duration_category": "half_day",
        "best_for": "Evening waterfront walks, photography, local street snacks, casual gatherings",
        "tags": "Waterfront, Lake Promenade, Sunset View, Evening Hub, City Landmark",
        "rating": 4.6,
        "family_friendly": 0.9,
        "nature_score": 0.85,
        "adventure_score": 0.2,
        "historical_score": 0.3,
        "spiritual_score": 0.1,
        "photography_score": 0.95,
        "food_score": 0.9,
        "entertainment_score": 0.8,
        "primary_experience": "relaxing",
        "preferred_groups": "solo,friends,family,couple",
        "distance_from_nagpur_center": 6.5,
        "best_time_to_visit": "05:00 PM - 09:00 PM",
        "opening_hours": "Open 24 Hours (Best during sunset hours)",
        "interesting_facts": "The lake was constructed in the 18th century by Nagpur's Bhonsle Kings as a major water reservoir.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Futala_Lake.jpg/1280px-Futala_Lake.jpg",
        "latitude": 21.1539,
        "longitude": 79.0475,
        "is_hidden_gem": 0,
        "nearby_food_name": "Futala Street Food & Matka Kulfi Hub",
        "nearby_food_id": "food-futala-kulfi"
    },
    {
        "name": "Deekshabhoomi Stupa",
        "category": "Historical",
        "description": "A world-renowned monument of architectural brilliance where Dr. B.R. Ambedkar embraced Buddhism. Features the largest hollow Buddhist stupa dome in Asia.",
        "location": "Bajaj Nagar, Nagpur, Maharashtra",
        "estimated_budget": 100,
        "budget_tier": "under_500",
        "ideal_duration_hours": 2.0,
        "duration_category": "half_day",
        "best_for": "Historical heritage, Buddhist architecture, peaceful meditation, cultural study",
        "tags": "Monuments, Heritage, Buddhist Stupa, Dholpur Sandstone, Peaceful",
        "rating": 4.8,
        "family_friendly": 1.0,
        "nature_score": 0.4,
        "adventure_score": 0.1,
        "historical_score": 1.0,
        "spiritual_score": 0.95,
        "photography_score": 0.85,
        "food_score": 0.3,
        "entertainment_score": 0.3,
        "primary_experience": "cultural",
        "preferred_groups": "solo,friends,family,couple",
        "distance_from_nagpur_center": 4.0,
        "best_time_to_visit": "08:00 AM - 06:00 PM",
        "opening_hours": "06:00 AM - 08:00 PM",
        "interesting_facts": "Built entirely out of Dholpur pink sandstone, the central dome hollow spans 120 feet in height.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Dheekshabhoomi_in_Nagpur.jpg/1280px-Dheekshabhoomi_in_Nagpur.jpg",
        "latitude": 21.1280,
        "longitude": 79.0669,
        "is_hidden_gem": 0,
        "nearby_food_name": "Haldiram's Shankar Nagar Food House",
        "nearby_food_id": "food-haldiram-shankar"
    },
    {
        "name": "Ambazari Lake & Garden",
        "category": "Nature",
        "description": "Nagpur's largest water body featuring expansive manicured lawns, walking trails, boating docks, and musical fountains. Origin point of the Nag River.",
        "location": "Ambazari, Near VNIT, Nagpur",
        "estimated_budget": 200,
        "budget_tier": "under_500",
        "ideal_duration_hours": 3.0,
        "duration_category": "half_day",
        "best_for": "Boating, morning fitness walks, family garden picnics, bird watching",
        "tags": "Lake, Public Garden, Boating, Nag River Source, Family Park",
        "rating": 4.5,
        "family_friendly": 0.95,
        "nature_score": 0.95,
        "adventure_score": 0.4,
        "historical_score": 0.2,
        "spiritual_score": 0.1,
        "photography_score": 0.8,
        "food_score": 0.5,
        "entertainment_score": 0.7,
        "primary_experience": "family",
        "preferred_groups": "family,couple,friends",
        "distance_from_nagpur_center": 7.0,
        "best_time_to_visit": "06:00 AM - 09:30 AM & 04:00 PM - 07:00 PM",
        "opening_hours": "06:00 AM - 07:30 PM",
        "interesting_facts": "Spanning over 15 square kilometers, the lake historically supplied drinking water to Nagpur city.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/AmbazariLake.JPG/1280px-AmbazariLake.JPG",
        "latitude": 21.1264,
        "longitude": 79.0435,
        "is_hidden_gem": 0,
        "nearby_food_name": "Dharampeth Street Food Court",
        "nearby_food_id": "food-dharampeth-street"
    },
    {
        "name": "Raman Science Centre & Planetarium",
        "category": "Science",
        "description": "Interactive science museum named in honor of Nobel Laureate Sir C.V. Raman. Features 3D scientific shows, prehistoric animal park, and digital planetarium.",
        "location": "Opposite Gandhisagar Lake, Subhash Road, Nagpur",
        "estimated_budget": 250,
        "budget_tier": "under_500",
        "ideal_duration_hours": 3.5,
        "duration_category": "half_day",
        "best_for": "Educational trips, science exhibits, planetarium astronomy, student learning",
        "tags": "Science Museum, Planetarium, 3D Exhibits, Educational, Family Science",
        "rating": 4.7,
        "family_friendly": 1.0,
        "nature_score": 0.3,
        "adventure_score": 0.3,
        "historical_score": 0.4,
        "spiritual_score": 0.0,
        "photography_score": 0.6,
        "food_score": 0.4,
        "entertainment_score": 0.9,
        "primary_experience": "family",
        "preferred_groups": "family,friends,solo",
        "distance_from_nagpur_center": 2.5,
        "best_time_to_visit": "10:30 AM - 05:00 PM",
        "opening_hours": "09:30 AM - 06:00 PM",
        "interesting_facts": "Affiliated with the National Council of Science Museums, hosting full-dome astronomy screenings daily.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Raman_Science_Centre_Nagpur.jpg/1280px-Raman_Science_Centre_Nagpur.jpg",
        "latitude": 21.1448,
        "longitude": 79.0911,
        "is_hidden_gem": 0,
        "nearby_food_name": "Keshav Tarri Poha Centre",
        "nearby_food_id": "food-keshav-poha"
    },
    {
        "name": "Seminary Hill & Japanese Rose Garden",
        "category": "Nature",
        "description": "Scenic hillock providing elevated panoramic views across Nagpur city skyline. Features the manicured Japanese Rose Garden with serene forest walking trails.",
        "location": "Seminary Hills, Nagpur",
        "estimated_budget": 150,
        "budget_tier": "under_500",
        "ideal_duration_hours": 2.5,
        "duration_category": "half_day",
        "best_for": "City panoramas, nature trails, rose photography, morning yoga",
        "tags": "Hilltop Vantage, Rose Garden, Forest Trail, Sunrise Spot, Scenic View",
        "rating": 4.6,
        "family_friendly": 0.85,
        "nature_score": 0.9,
        "adventure_score": 0.4,
        "historical_score": 0.2,
        "spiritual_score": 0.2,
        "photography_score": 0.9,
        "food_score": 0.4,
        "entertainment_score": 0.5,
        "primary_experience": "relaxing",
        "preferred_groups": "couple,friends,solo,family",
        "distance_from_nagpur_center": 5.0,
        "best_time_to_visit": "06:00 AM - 09:00 AM & 04:30 PM - 06:30 PM",
        "opening_hours": "06:00 AM - 07:00 PM",
        "interesting_facts": "Named after the historic St. Charles Seminary located atop the plateau since colonial times.",
        "image_url": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=1200&q=80",
        "latitude": 21.1661,
        "longitude": 79.0612,
        "is_hidden_gem": 0,
        "nearby_food_name": "Civil Lines Heritage Cafe",
        "nearby_food_id": "food-civil-lines-cafe"
    },
    {
        "name": "Dragon Palace Temple (Kamptee)",
        "category": "Spiritual",
        "description": "Also known as the Lotus Temple of Nagpur, showcasing pristine white marble architecture, landscaped Japanese Zen gardens, and quiet meditation halls.",
        "location": "Kamptee, 16 km from Nagpur Center",
        "estimated_budget": 300,
        "budget_tier": "under_500",
        "ideal_duration_hours": 3.0,
        "duration_category": "half_day",
        "best_for": "Buddhist architecture, spiritual meditation, landscaped garden walks",
        "tags": "Lotus Architecture, White Marble, Zen Garden, Meditation, Peaceful",
        "rating": 4.7,
        "family_friendly": 0.95,
        "nature_score": 0.7,
        "adventure_score": 0.1,
        "historical_score": 0.5,
        "spiritual_score": 1.0,
        "photography_score": 0.9,
        "food_score": 0.3,
        "entertainment_score": 0.3,
        "primary_experience": "cultural",
        "preferred_groups": "family,couple,solo",
        "distance_from_nagpur_center": 16.0,
        "best_time_to_visit": "08:00 AM - 12:00 PM & 04:00 PM - 07:00 PM",
        "opening_hours": "06:00 AM - 08:00 PM",
        "interesting_facts": "Inaugurated in 1999, housing a historical Buddha statue carved out of a single sandalwood log.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Dragon_Palace_Temple.jpg/1280px-Dragon_Palace_Temple.jpg",
        "latitude": 21.2263,
        "longitude": 79.1984,
        "is_hidden_gem": 0,
        "nearby_food_name": "Kamptee Dhaba & Highway Sweets",
        "nearby_food_id": "food-kamptee-dhaba"
    },
    {
        "name": "Sitabuldi Fort",
        "category": "Historical",
        "description": "Historic hill citadel site of the crucial 1817 Battle of Sitabuldi between the British East India Company and Appasaheb Bhonsle. Located in central Nagpur.",
        "location": "Sitabuldi, Central Nagpur",
        "estimated_budget": 100,
        "budget_tier": "under_500",
        "ideal_duration_hours": 2.0,
        "duration_category": "half_day",
        "best_for": "Military history, British era architecture, city center landmark",
        "tags": "Historic Fort, 1817 Battle, Bhonsle Heritage, Central Landmark",
        "rating": 4.4,
        "family_friendly": 0.8,
        "nature_score": 0.3,
        "adventure_score": 0.3,
        "historical_score": 0.95,
        "spiritual_score": 0.1,
        "photography_score": 0.75,
        "food_score": 0.3,
        "entertainment_score": 0.4,
        "primary_experience": "exploring",
        "preferred_groups": "solo,friends,family",
        "distance_from_nagpur_center": 1.0,
        "best_time_to_visit": "09:00 AM - 04:00 PM (Select open access days)",
        "opening_hours": "Restricted Access (Open on major national holidays)",
        "interesting_facts": "Mahatma Gandhi was briefly detained at this fort following his arrest in 1923 during Freedom struggle movements.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Sitabuldi_fort_gate.JPG/1280px-Sitabuldi_fort_gate.JPG",
        "latitude": 21.1472,
        "longitude": 79.0836,
        "is_hidden_gem": 0,
        "nearby_food_name": "Sitabuldi Main Street Food Lane",
        "nearby_food_id": "food-sitabuldi-street"
    },
    {
        "name": "Narrow Gauge Rail Museum",
        "category": "Historical",
        "description": "Unique railway heritage museum showcasing antique narrow-gauge steam locomotives, vintage wooden passenger coaches, and historical signaling artifacts.",
        "location": "Kamptee Road, Moti Bagh, Nagpur",
        "estimated_budget": 150,
        "budget_tier": "under_500",
        "ideal_duration_hours": 2.5,
        "duration_category": "half_day",
        "best_for": "Railway heritage, antique steam locomotives, vintage exhibits",
        "tags": "Railway Museum, Steam Engines, Vintage Locomotives, Heritage Park",
        "rating": 4.5,
        "family_friendly": 0.95,
        "nature_score": 0.4,
        "adventure_score": 0.2,
        "historical_score": 0.85,
        "spiritual_score": 0.0,
        "photography_score": 0.85,
        "food_score": 0.3,
        "entertainment_score": 0.7,
        "primary_experience": "family",
        "preferred_groups": "family,friends,solo",
        "distance_from_nagpur_center": 3.0,
        "best_time_to_visit": "03:00 PM - 07:00 PM",
        "opening_hours": "02:30 PM - 08:00 PM (Closed Mondays)",
        "interesting_facts": "Maintains an operational mini toy train circuit traveling around the garden museum perimeter.",
        "image_url": "https://images.unsplash.com/photo-1515165562839-978bbcf18277?auto=format&fit=crop&w=1200&q=80",
        "latitude": 21.1625,
        "longitude": 79.0888,
        "is_hidden_gem": 0,
        "nearby_food_name": "Haldiram's Kamptee Road Outlet",
        "nearby_food_id": "food-haldiram-shankar"
    },
    {
        "name": "Gorewada International Bio Park & Safari",
        "category": "Nature",
        "description": "Spanning over 1900 hectares of protected forest, offering jungle leopard safaris, herbivore safaris, wildlife rescue facilities, and scenic lake trails.",
        "location": "Katol Road, Gorewada, Nagpur",
        "estimated_budget": 750,
        "budget_tier": "500_1000",
        "ideal_duration_hours": 4.5,
        "duration_category": "1_day",
        "best_for": "Wild leopard safaris, forest conservation, birding trails, eco-tourism",
        "tags": "Bio Park, Jungle Safari, Wildlife Conservation, Teak Forest",
        "rating": 4.7,
        "family_friendly": 0.9,
        "nature_score": 1.0,
        "adventure_score": 0.9,
        "historical_score": 0.1,
        "spiritual_score": 0.0,
        "photography_score": 0.95,
        "food_score": 0.5,
        "entertainment_score": 0.85,
        "primary_experience": "adventure",
        "preferred_groups": "family,friends,couple,solo",
        "distance_from_nagpur_center": 11.0,
        "best_time_to_visit": "06:00 AM - 10:00 AM & 03:00 PM - 06:00 PM",
        "opening_hours": "06:00 AM - 06:00 PM (Scheduled safari slots)",
        "interesting_facts": "Recognized as Balasaheb Thackeray Gorewada International Zoological Park, among Asia's largest safari parks.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/b/bd/Gorewada_lake4.jpg",
        "latitude": 21.1965,
        "longitude": 79.0345,
        "is_hidden_gem": 0,
        "nearby_food_name": "Katol Road Highway Dhaba",
        "nearby_food_id": "food-saoji-joint"
    },
    {
        "name": "Khekranala Dam & Reservoir Trek",
        "category": "Adventure",
        "description": "Situated in the Khapa forest foothills, featuring a clear reservoir lake bounded by wooded ridges. Ideal spot for forest trekking, water views, and weekend camping.",
        "location": "Khapa Forest Range, 55 km from Nagpur",
        "estimated_budget": 800,
        "budget_tier": "500_1000",
        "ideal_duration_hours": 6.0,
        "duration_category": "1_day",
        "best_for": "Ridge trekking, reservoir views, forest camping, landscape photography",
        "tags": "Reservoir Dam, Forest Trek, Foothills, Camping, Nature Excursion",
        "rating": 4.6,
        "family_friendly": 0.75,
        "nature_score": 0.95,
        "adventure_score": 0.95,
        "historical_score": 0.1,
        "spiritual_score": 0.0,
        "photography_score": 0.9,
        "food_score": 0.4,
        "entertainment_score": 0.6,
        "primary_experience": "adventure",
        "preferred_groups": "friends,solo,couple",
        "distance_from_nagpur_center": 55.0,
        "best_time_to_visit": "Monsoon & Winter (July to February)",
        "opening_hours": "07:00 AM - 06:00 PM",
        "interesting_facts": "The forest ecosystem surrounding Khekranala reservoir harbors diverse bird species and medicinal flora.",
        "image_url": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
        "latitude": 21.4550,
        "longitude": 79.0333,
        "is_hidden_gem": 0,
        "nearby_food_name": "Khapa Forest Resort Dhaba",
        "nearby_food_id": "food-saoji-joint"
    },
    {
        "name": "Pench National Park (Silari Gate Expedition)",
        "category": "Nature",
        "description": "The wildlife sanctuary that inspired Rudyard Kipling's 'The Jungle Book'. World-famous tiger reserve providing open jeep safaris across teak forests and river habitats.",
        "location": "Silari Gate, Nagpur-Jabalpur Highway (82 km from Nagpur)",
        "estimated_budget": 2500,
        "budget_tier": "above_2000",
        "ideal_duration_hours": 12.0,
        "duration_category": "2_days",
        "best_for": "Royal Bengal tiger tracking, wildlife photography, jungle resort stays",
        "tags": "Tiger Reserve, Jungle Book, Open Jeep Safari, Teak Woods",
        "rating": 4.9,
        "family_friendly": 0.85,
        "nature_score": 1.0,
        "adventure_score": 1.0,
        "historical_score": 0.2,
        "spiritual_score": 0.0,
        "photography_score": 1.0,
        "food_score": 0.6,
        "entertainment_score": 0.9,
        "primary_experience": "adventure",
        "preferred_groups": "friends,family,couple,solo",
        "distance_from_nagpur_center": 82.0,
        "best_time_to_visit": "October to June (Morning & Afternoon Safari)",
        "opening_hours": "06:00 AM - 11:00 AM & 03:00 PM - 06:30 PM",
        "interesting_facts": "Pench River flows directly through the center of the park, dividing it into eastern and western sanctuary zones.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Pench_Safari.jpg/1280px-Pench_Safari.jpg",
        "latitude": 21.6500,
        "longitude": 79.3000,
        "is_hidden_gem": 0,
        "nearby_food_name": "Silari Gate Jungle Resort Dining",
        "nearby_food_id": "food-saoji-joint"
    },
    {
        "name": "Ramtek Fort Temple & Kalidas Smarak",
        "category": "Historical",
        "description": "Perched atop a hill fort, Ramtek is associated with Lord Rama's exile and is where Sanskrit poet Kalidas composed his masterpiece 'Meghdoot'. Offers hill architecture and valley views.",
        "location": "Ramtek, 48 km from Nagpur City",
        "estimated_budget": 600,
        "budget_tier": "500_1000",
        "ideal_duration_hours": 5.0,
        "duration_category": "1_day",
        "best_for": "Ancient hill fort architecture, literary history, valley overlooks",
        "tags": "Hill Fort, Ram Temple, Kalidas Heritage, Ancient Architecture",
        "rating": 4.7,
        "family_friendly": 0.95,
        "nature_score": 0.75,
        "adventure_score": 0.4,
        "historical_score": 0.95,
        "spiritual_score": 0.95,
        "photography_score": 0.85,
        "food_score": 0.5,
        "entertainment_score": 0.4,
        "primary_experience": "cultural",
        "preferred_groups": "family,couple,solo,friends",
        "distance_from_nagpur_center": 48.0,
        "best_time_to_visit": "07:00 AM - 05:00 PM",
        "opening_hours": "06:00 AM - 08:00 PM",
        "interesting_facts": "The fort citadel stands on a steep rocky ridge, offering panoramic vistas over Ambala Lake.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Spire_of_Main_Shrine_-_Ram_Temple%2C_Ramtek.JPG/1280px-Spire_of_Main_Shrine_-_Ram_Temple%2C_Ramtek.JPG",
        "latitude": 21.3970,
        "longitude": 79.3300,
        "is_hidden_gem": 0,
        "nearby_food_name": "Ramtek Hilltop Prashad & Dhaba",
        "nearby_food_id": "food-kamptee-dhaba"
    },
    {
        "name": "Umred Karhandla Wildlife Sanctuary",
        "category": "Nature",
        "description": "Prominent tiger sanctuary near Nagpur, famous for sightings of wild tigers, leopards, sloth bears, wild dogs, and gaur across grassland habitats.",
        "location": "Umred, 58 km from Nagpur",
        "estimated_budget": 1800,
        "budget_tier": "1000_2000",
        "ideal_duration_hours": 6.0,
        "duration_category": "1_day",
        "best_for": "Tiger tracking, bird photography, day jeep safaris",
        "tags": "Wildlife Sanctuary, Tiger Tracking, Safari, Grasslands",
        "rating": 4.6,
        "family_friendly": 0.85,
        "nature_score": 0.95,
        "adventure_score": 0.9,
        "historical_score": 0.1,
        "spiritual_score": 0.0,
        "photography_score": 0.95,
        "food_score": 0.4,
        "entertainment_score": 0.75,
        "primary_experience": "adventure",
        "preferred_groups": "friends,family,couple",
        "distance_from_nagpur_center": 58.0,
        "best_time_to_visit": "November to May",
        "opening_hours": "06:00 AM - 10:00 AM & 02:30 PM - 06:00 PM",
        "interesting_facts": "Serves as an essential ecological tiger corridor connecting Tadoba-Andhari and Pench reserves.",
        "image_url": "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=1200&q=80",
        "latitude": 20.8500,
        "longitude": 79.4300,
        "is_hidden_gem": 0,
        "nearby_food_name": "Umred Safari Dhaba",
        "nearby_food_id": "food-saoji-joint"
    },
    {
        "name": "Swaminarayan Temple (BAPS Nagpur)",
        "category": "Spiritual",
        "description": "Architectural masterpiece crafted from pink Dholpur sandstone, featuring detailed stone carvings, marble inner sanctum, illuminated fountains, and pristine gardens.",
        "location": "Wathoda, Ring Road, Nagpur",
        "estimated_budget": 150,
        "budget_tier": "under_500",
        "ideal_duration_hours": 2.5,
        "duration_category": "half_day",
        "best_for": "Pink stone carving architecture, evening illumination, family visits",
        "tags": "Pink Stone Temple, Stone Carvings, Vedic Architecture, Gardens",
        "rating": 4.8,
        "family_friendly": 1.0,
        "nature_score": 0.5,
        "adventure_score": 0.0,
        "historical_score": 0.6,
        "spiritual_score": 1.0,
        "photography_score": 0.95,
        "food_score": 0.6,
        "entertainment_score": 0.4,
        "primary_experience": "cultural",
        "preferred_groups": "family,couple,solo",
        "distance_from_nagpur_center": 8.0,
        "best_time_to_visit": "05:00 PM - 08:30 PM (Evening lighting is recommended)",
        "opening_hours": "07:30 AM - 12:00 PM & 04:00 PM - 08:30 PM",
        "interesting_facts": "Constructed according to ancient Shilpa Shastras without using structural steel support beams.",
        "image_url": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
        "latitude": 21.1355,
        "longitude": 79.1456,
        "is_hidden_gem": 0,
        "nearby_food_name": "Premvati Pure Veg Food Dining",
        "nearby_food_id": "food-haldiram-shankar"
    },
    {
        "name": "Telankhedi Hanuman Temple & Lake Park",
        "category": "Spiritual",
        "description": "Revered temple beside Telankhedi Lake, surrounded by local floral markets, food stalls, and a public park overlooking the water.",
        "location": "Telankhedi, Near Futala, Nagpur",
        "estimated_budget": 200,
        "budget_tier": "under_500",
        "ideal_duration_hours": 2.0,
        "duration_category": "half_day",
        "best_for": "Lakeside temple visit, evening snacks, garden strolls",
        "tags": "Lakeside Temple, Hanuman Shrine, Public Garden, Evening Snacks",
        "rating": 4.6,
        "family_friendly": 0.95,
        "nature_score": 0.65,
        "adventure_score": 0.1,
        "historical_score": 0.5,
        "spiritual_score": 0.9,
        "photography_score": 0.75,
        "food_score": 0.8,
        "entertainment_score": 0.6,
        "primary_experience": "family",
        "preferred_groups": "family,solo,friends,couple",
        "distance_from_nagpur_center": 6.0,
        "best_time_to_visit": "07:00 AM - 10:00 AM & 05:00 PM - 08:30 PM",
        "opening_hours": "06:00 AM - 09:00 PM",
        "interesting_facts": "The historic deity idol of Sankat Mochan Hanuman has been worshipped beside Telankhedi lake for generations.",
        "image_url": "https://images.unsplash.com/photo-1600100397608-f010f423b971?auto=format&fit=crop&w=1200&q=80",
        "latitude": 21.1550,
        "longitude": 79.0510,
        "is_hidden_gem": 0,
        "nearby_food_name": "Futala Lake Matka Kulfi Hub",
        "nearby_food_id": "food-futala-kulfi"
    },
    {
        "name": "Haldiram's Food Hub & Nagpur Culinary Street",
        "category": "Food",
        "description": "Flagship culinary center of the Haldiram's brand originating in Nagpur. Experience authentic spicy Saoji curries, Nagpur orange barfi, samosas, and regional sweets.",
        "location": "Shankar Nagar / Wardha Road Hubs, Nagpur",
        "estimated_budget": 450,
        "budget_tier": "under_500",
        "ideal_duration_hours": 2.0,
        "duration_category": "half_day",
        "best_for": "Nagpur Saoji cuisine, Orange Barfi tasting, regional snacks & sweets",
        "tags": "Saoji Cuisine, Orange Barfi, Foodie Destination, Haldiram Origin",
        "rating": 4.7,
        "family_friendly": 1.0,
        "nature_score": 0.1,
        "adventure_score": 0.1,
        "historical_score": 0.3,
        "spiritual_score": 0.0,
        "photography_score": 0.7,
        "food_score": 1.0,
        "entertainment_score": 0.8,
        "primary_experience": "family",
        "preferred_groups": "family,friends,couple,solo",
        "distance_from_nagpur_center": 4.5,
        "best_time_to_visit": "12:30 PM - 03:30 PM & 07:00 PM - 10:30 PM",
        "opening_hours": "09:00 AM - 11:00 PM",
        "interesting_facts": "Nagpur is famed as India's 'Orange City', and Haldiram's signature Orange Barfi sweet was created right here.",
        "image_url": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80",
        "latitude": 21.1340,
        "longitude": 79.0680,
        "is_hidden_gem": 0,
        "nearby_food_name": "Haldiram's Shankar Nagar Flagship House",
        "nearby_food_id": "food-haldiram-shankar"
    },
    {
        "name": "Adasa Ganpati Temple Complex",
        "category": "Spiritual",
        "description": "Ancient pilgrimage site featuring one of Vidarbha's Ashta-Vinayaka Ganesha temples, set on a hilltop surrounded by 45 monolithic stone shrines.",
        "location": "Adasa Village, 35 km from Nagpur",
        "estimated_budget": 400,
        "budget_tier": "under_500",
        "ideal_duration_hours": 4.0,
        "duration_category": "half_day",
        "best_for": "Ancient stone sculpture, Ganesha pilgrimage, peaceful countryside",
        "tags": "Ancient Stone Shrines, Ganesha Temple, Monolithic Sculptures",
        "rating": 4.7,
        "family_friendly": 0.95,
        "nature_score": 0.6,
        "adventure_score": 0.2,
        "historical_score": 0.9,
        "spiritual_score": 1.0,
        "photography_score": 0.8,
        "food_score": 0.4,
        "entertainment_score": 0.3,
        "primary_experience": "cultural",
        "preferred_groups": "family,couple,solo",
        "distance_from_nagpur_center": 35.0,
        "best_time_to_visit": "07:00 AM - 01:00 PM",
        "opening_hours": "06:00 AM - 08:00 PM",
        "interesting_facts": "Houses a 12-foot tall monolithic Ganesha idol carved out of a single rock block.",
        "image_url": "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=1200&q=80",
        "latitude": 21.3200,
        "longitude": 78.9600,
        "is_hidden_gem": 0,
        "nearby_food_name": "Adasa Pilgrimage Maharashtrian Dining",
        "nearby_food_id": "food-keshav-poha"
    },
    {
        "name": "Zero Mile Stone Landmark",
        "category": "Historical",
        "description": "Geographical center marker of undivided colonial India, built in 1907 by the Great Trigonometrical Survey of India featuring sandstone pillar and horse statues.",
        "location": "Civil Lines, Near Residency Road, Nagpur",
        "estimated_budget": 50,
        "budget_tier": "under_500",
        "ideal_duration_hours": 1.0,
        "duration_category": "half_day",
        "best_for": "Historical monument photography, geographical interest, central landmark",
        "tags": "Center of India, British Survey Marker, Sandstone Pillar, Historic Landmark",
        "rating": 4.2,
        "family_friendly": 0.85,
        "nature_score": 0.2,
        "adventure_score": 0.1,
        "historical_score": 0.95,
        "spiritual_score": 0.0,
        "photography_score": 0.8,
        "food_score": 0.2,
        "entertainment_score": 0.3,
        "primary_experience": "exploring",
        "preferred_groups": "solo,friends,family",
        "distance_from_nagpur_center": 0.5,
        "best_time_to_visit": "09:00 AM - 06:00 PM",
        "opening_hours": "Open 24 Hours",
        "interesting_facts": "Distances to all major cities across British India were calculated starting from this exact stone pillar.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/2/23/Zero_mile_nagpur.jpg",
        "latitude": 21.1497,
        "longitude": 79.0806,
        "is_hidden_gem": 0,
        "nearby_food_name": "Civil Lines Residency Cafe & Bakery",
        "nearby_food_id": "food-civil-lines-cafe"
    },
    {
        "name": "Waki Woods Adventure Camp",
        "category": "Adventure",
        "description": "Countryside riverbank retreat on the Kanhan River, offering log cabins, boating, ziplining, archery, and outdoor camping.",
        "location": "Waki, 30 km from Nagpur Center",
        "estimated_budget": 1200,
        "budget_tier": "1000_2000",
        "ideal_duration_hours": 6.0,
        "duration_category": "1_day",
        "best_for": "Riverbank camping, ziplining, outdoor group picnics, river kayaking",
        "tags": "Kanhan Riverbank, Camping, Zipline, Log Cabins, Outdoor Camp",
        "rating": 4.5,
        "family_friendly": 0.85,
        "nature_score": 0.9,
        "adventure_score": 0.95,
        "historical_score": 0.1,
        "spiritual_score": 0.0,
        "photography_score": 0.85,
        "food_score": 0.6,
        "entertainment_score": 0.9,
        "primary_experience": "adventure",
        "preferred_groups": "friends,family,couple",
        "distance_from_nagpur_center": 30.0,
        "best_time_to_visit": "09:00 AM - 06:00 PM",
        "opening_hours": "08:00 AM - 07:00 PM",
        "interesting_facts": "Surrounded by quiet birding habitats along the Kanhan river delta with native avian species.",
        "image_url": "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=1200&q=80",
        "latitude": 21.3100,
        "longitude": 79.1200,
        "is_hidden_gem": 0,
        "nearby_food_name": "Kanhan Riverbank Dhaba",
        "nearby_food_id": "food-saoji-joint"
    },
    {
        "name": "Kasturchand Park & Civil Lines Boulevard",
        "category": "Entertainment",
        "description": "Nagpur's largest open heritage grounds hosting sports and expos, surrounded by colonial British architecture, tree-canopied avenues, and boutique cafes.",
        "location": "Civil Lines, Nagpur",
        "estimated_budget": 200,
        "budget_tier": "under_500",
        "ideal_duration_hours": 2.0,
        "duration_category": "half_day",
        "best_for": "Civil Lines tree-lined walks, heritage avenues, cafes, open park",
        "tags": "Civil Lines, Heritage Avenue, Open Park, Tree Canopy, Cafes",
        "rating": 4.4,
        "family_friendly": 0.9,
        "nature_score": 0.6,
        "adventure_score": 0.2,
        "historical_score": 0.7,
        "spiritual_score": 0.0,
        "photography_score": 0.8,
        "food_score": 0.75,
        "entertainment_score": 0.7,
        "primary_experience": "relaxing",
        "preferred_groups": "friends,solo,couple,family",
        "distance_from_nagpur_center": 1.5,
        "best_time_to_visit": "05:00 PM - 08:30 PM",
        "opening_hours": "Open 24 Hours",
        "interesting_facts": "Historic central sports ground of Nagpur hosting civic rallies and tournaments for over a century.",
        "image_url": "https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=1200&q=80",
        "latitude": 21.1550,
        "longitude": 79.0830,
        "is_hidden_gem": 0,
        "nearby_food_name": "Civil Lines Heritage Cafe",
        "nearby_food_id": "food-civil-lines-cafe"
    },
    # --- AUTHENTIC NAGPUR HIDDEN GEMS & BEST FOOD SPOTS ---
    {
        "name": "Sonegaon Lake & Heritage Stepwell",
        "category": "Nature",
        "description": "A tranquil local hidden gem away from tourist crowds. Features a historical stepwell built by Bhonsle rulers and quiet lakeside walking paths.",
        "location": "Sonegaon, Nagpur (Near Airport)",
        "estimated_budget": 100,
        "budget_tier": "under_500",
        "ideal_duration_hours": 1.5,
        "duration_category": "half_day",
        "best_for": "Quiet sunset watching, heritage stepwell photography, peaceful walk",
        "tags": "Hidden Gem, Stepwell, Peaceful Lake, Local Secret, Sunset Spot",
        "rating": 4.5,
        "family_friendly": 0.9,
        "nature_score": 0.9,
        "adventure_score": 0.2,
        "historical_score": 0.8,
        "spiritual_score": 0.2,
        "photography_score": 0.85,
        "food_score": 0.3,
        "entertainment_score": 0.4,
        "primary_experience": "relaxing",
        "preferred_groups": "solo,couple,friends",
        "distance_from_nagpur_center": 8.5,
        "best_time_to_visit": "05:30 PM - 07:00 PM",
        "opening_hours": "Open 24 Hours",
        "interesting_facts": "Houses an 18th-century stone stepwell (Baoli) constructed during the Maratha Bhonsle era.",
        "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
        "latitude": 21.0950,
        "longitude": 79.0550,
        "is_hidden_gem": 1,
        "nearby_food_name": "Wardha Road Food Square",
        "nearby_food_id": "food-haldiram-shankar"
    },
    {
        "name": "Keshav Tarri Poha & Saoji Culinary Hub",
        "category": "Food",
        "description": "Nagpur's ultimate breakfast spot famous for fiery Tarri Poha (rice flakes in spicy chickpea gravy), roasted samosas, and authentic Saoji curries.",
        "location": "Deo Nagar / Sitabuldi, Nagpur",
        "estimated_budget": 150,
        "budget_tier": "under_500",
        "ideal_duration_hours": 1.0,
        "duration_category": "half_day",
        "best_for": "Authentic Nagpur Tarri Poha breakfast, local street food culture, Saoji spice",
        "tags": "Tarri Poha, Iconic Breakfast, Saoji Curry, Best Local Food, Nagpur Special",
        "rating": 4.8,
        "family_friendly": 0.95,
        "nature_score": 0.1,
        "adventure_score": 0.2,
        "historical_score": 0.3,
        "spiritual_score": 0.0,
        "photography_score": 0.7,
        "food_score": 1.0,
        "entertainment_score": 0.7,
        "primary_experience": "family",
        "preferred_groups": "solo,friends,family,couple",
        "distance_from_nagpur_center": 2.0,
        "best_time_to_visit": "07:30 AM - 11:30 AM",
        "opening_hours": "07:00 AM - 10:30 PM",
        "interesting_facts": "Tarri Poha with extra black chickpea gravy is considered the unofficial national breakfast of Nagpur.",
        "image_url": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80",
        "latitude": 21.1400,
        "longitude": 79.0800,
        "is_hidden_gem": 0,
        "nearby_food_name": "Keshav Tarri Poha Centre",
        "nearby_food_id": "food-keshav-poha"
    },
    {
        "name": "Civil Lines Heritage Banyan Walk",
        "category": "Nature",
        "description": "A serene green corridor lined with century-old Banyan trees, colonial bungalows, and quiet shaded pathways in Nagpur's historic Civil Lines district.",
        "location": "Residency Road, Civil Lines, Nagpur",
        "estimated_budget": 50,
        "budget_tier": "under_500",
        "ideal_duration_hours": 1.5,
        "duration_category": "half_day",
        "best_for": "Morning jogging, tree canopy photography, heritage stroll",
        "tags": "Hidden Gem, Banyan Tree Canopy, Colonial District, Peaceful Walk",
        "rating": 4.6,
        "family_friendly": 0.9,
        "nature_score": 0.85,
        "adventure_score": 0.1,
        "historical_score": 0.75,
        "spiritual_score": 0.1,
        "photography_score": 0.85,
        "food_score": 0.4,
        "entertainment_score": 0.5,
        "primary_experience": "relaxing",
        "preferred_groups": "solo,couple,friends",
        "distance_from_nagpur_center": 1.2,
        "best_time_to_visit": "06:30 AM - 09:00 AM & 05:00 PM - 07:00 PM",
        "opening_hours": "Open 24 Hours",
        "interesting_facts": "The massive banyan trees along Civil Lines were planted during the British Central Provinces administration.",
        "image_url": "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80",
        "latitude": 21.1540,
        "longitude": 79.0770,
        "is_hidden_gem": 1,
        "nearby_food_name": "Civil Lines Heritage Cafe & Bakery",
        "nearby_food_id": "food-civil-lines-cafe"
    }
]

def seed_database():
    """Initializes schema and seeds SQLite database with 23 authentic Nagpur destinations."""
    init_db_schema()
    conn = get_db_connection()
    cursor = conn.cursor()

    cursor.execute("DELETE FROM destinations")

    insert_query = '''
        INSERT INTO destinations (
            name, category, description, location, estimated_budget, budget_tier,
            ideal_duration_hours, duration_category, best_for, tags, rating,
            family_friendly, nature_score, adventure_score, historical_score,
            spiritual_score, photography_score, food_score, entertainment_score,
            primary_experience, preferred_groups, distance_from_nagpur_center,
            best_time_to_visit, opening_hours, interesting_facts, image_url,
            latitude, longitude, is_hidden_gem, nearby_food_name, nearby_food_id
        ) VALUES (
            ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
        )
    '''

    for d in NAGPUR_DESTINATIONS:
        cursor.execute(insert_query, (
            d["name"], d["category"], d["description"], d["location"],
            d["estimated_budget"], d["budget_tier"], d["ideal_duration_hours"],
            d["duration_category"], d["best_for"], d["tags"], d["rating"],
            d["family_friendly"], d["nature_score"], d["adventure_score"],
            d["historical_score"], d["spiritual_score"], d["photography_score"],
            d["food_score"], d["entertainment_score"], d["primary_experience"],
            d["preferred_groups"], d["distance_from_nagpur_center"],
            d["best_time_to_visit"], d["opening_hours"], d["interesting_facts"],
            d["image_url"], d["latitude"], d["longitude"], d.get("is_hidden_gem", 0),
            d.get("nearby_food_name", "Haldiram's Food Hub"), d.get("nearby_food_id", "food-haldiram-shankar")
        ))

    conn.commit()
    conn.close()
    print(f"TripMitra AI: Successfully seeded database with {len(NAGPUR_DESTINATIONS)} destinations (with exact Lat/Lng coordinates & food links)!")

if __name__ == "__main__":
    seed_database()
